-- Maximo Sales Calculator — Supabase/PostgreSQL schema
-- Equivalent database shape to the current Drizzle MySQL schema.
-- Apply through Supabase SQL Editor or: supabase db push

begin;

do $$
begin
  create type public.user_role as enum ('user', 'admin');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  "openId" varchar(64) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  "branchName" varchar(128) not null,
  species varchar(128) not null,
  "nominalSize" varchar(32),
  profile varchar(256),
  "stockLf" integer not null default 0,
  "lastSyncedAt" timestamptz not null default now(),
  "lengthFt" integer,
  pieces integer
);

create table if not exists public."inventorySyncLog" (
  id bigint generated by default as identity primary key,
  "syncedAt" timestamptz not null default now(),
  "rowsUpserted" integer not null default 0,
  status varchar(32) not null default 'success',
  "errorMessage" text
);

commit;
